[build]
  command = "cd webapp && npm run build"
  publish = "webapp/dist"

[functions]
  directory = "webapp/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
